mysite_env/mysite/login/urls.py
#-*- codeing=uft-8 -*-
#@Time: 2020/5/18 16:38
#@Author:陈怡婧
#@File ：urls.py
#@Software:PyCharm


from django.urls import path,include,re_path
from . import views

app_name='login'
urlpatterns = [
    path('',views.homepage,name='主页'), #视窗来处理相应
    path('login/',views.log_in,name='登录'), #视窗来处理相应
    path('logout/',views.log_out,name='退出'), #视窗来处理相应
    path('register/',views.register,name='注册'), #视窗来处理相应
    re_path('user_center/$',views.user_center,name='个人中心'), #视窗来处理相应
    re_path('user_center/edit_profile/$',views.edit_profile,name='编辑个人信息'), #视窗来处理相应
    path('user_center/change_password', views.change_password, name='修改密码'),  # 视窗来处理相应
    re_path('ticket/$', views.ticket_information, name='车票信息'),  # 视窗来处理相应
    path('base/', views.base, name='首页'),  # 视窗来处理相应
    re_path('buy/$', views.buy_information, name='购买车票'),  # 视窗来处理相应
    re_path('bought/$', views.bought_information, name='已购车票'),  # 视窗来处理相应
    re_path('ticket_change/$', views.ticket_change, name='票务修改'),  # 视窗来处理相应
    re_path('ticket_detail_change/$', views.ticket_detail_change, name='车票详细信息修改'),  # 视窗来处理相应
    re_path('ticket_create/$', views.ticket_create, name='新增车票'),  # 视窗来处理相应
    re_path('ticket_delete/$', views.ticket_delete, name='删除车票'),  # 视窗来处理相应
    path('code/', views.code_confirm, name='短信验证码'),  # 视窗来处理相应
    re_path('modify_detail/$', views.modify_detail, name='记录查询'),  # 视窗来处理相应
]

mysite_env/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
import login.urls

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('login.urls')),#交给登录app来处理
    path('captcha/', include('captcha.urls')),
]

mysite_env/mysite/login/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
# Create your models here.

class registry(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100)
    password=models.CharField(max_length=100)
    email=models.EmailField(max_length=100)

class ticket(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100)
    src=models.CharField(max_length=100)
    det=models.CharField(max_length=100)
    date=models.DateField(max_length=100)
    soft=models.IntegerField()
    softprice = models.CharField(max_length=100)
    hard = models.IntegerField()
    hardprice = models.CharField(max_length=100)
    hardseat = models.IntegerField()
    hardseatprice = models.CharField(max_length=100)

class bought_ticket(models.Model):
    id = models.AutoField(primary_key=True)
    tid = models.IntegerField()
    tname=models.CharField(max_length=100)
    tsrc=models.CharField(max_length=100)
    tdet=models.CharField(max_length=100)
    tdate=models.DateField(max_length=100)
    type = models.CharField(max_length=100)
    num = models.IntegerField()
    name = models.CharField(max_length=100)
    realname = models.CharField(max_length=100)
    idnum = models.CharField(max_length=100)
    buytime=models.DateTimeField(default=datetime.now)

class admincode(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100)
    realname = models.CharField(max_length=100)
    idnum = models.CharField(max_length=100)
    check=models.CharField(max_length=100)


class modify(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    tid = models.CharField(max_length=100)
    type=models.CharField(max_length=100)
    modifytime=models.DateTimeField(default=datetime.now)

mysite_env/mysite/login/forms.py
#-*- codeing=uft-8 -*-
#@Time: 2020/5/18 22:30
#@Author:陈怡婧
#@File ：forms.py
#@Software:PyCharm

from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django import forms
from django.contrib.auth.models import User
from captcha.fields import CaptchaField

class new_register_form(UserCreationForm):#自定义注册表单
    昵称=forms.CharField(required=False,max_length=50)
    生日=forms.DateField(required=False)
    captcha=CaptchaField()
    class Meta:
        model=User
        fields=('username','password1','password2','email','昵称','生日')

class new_edit_form(UserChangeForm):#自定义编辑表单
    昵称=forms.CharField(required=False,max_length=50)
    生日=forms.DateField(required=False)

    class Meta:
        model=User
        fields=('username','password','email','昵称','生日')

class captcha_form(forms.Form):
    captcha = CaptchaField(label='验证码',
        required=True,
        error_messages={
            'required': '验证码不能为空'
        })

mysite_env/mysite/login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,PasswordChangeForm
from django.contrib import messages
from .forms import captcha_form
from django.http import HttpResponse
from .models import registry,ticket,bought_ticket,admincode,modify
from datetime import datetime
from .send_sms import send_sms
from random import randint
import time

# Create your views here.

#创建登录界面函数，并且把网页返回给用户
def homepage(request):
    if request.GET.get('obj')is not None:
        context={'obj':request.GET.get('obj')}
        return render(request,'login/homepage.html',context)
    else:
        context = {'error': '注意，检测到您还未登录，请先登录'}
        return render(request, 'login/homepage.html', context)

def code_confirm(request):#根据用户输入的手机号给用户手机发送验证码
    if request.method=='GET':
        if time.time()>request.session.get('overtime',0):
            code = '%d' % randint(100000, 999999)#生成要发送的验证码
            request.session['code']=code
            request.session['resend_time'] = time.time()+60
            request.session['overtime'] = time.time() + 120
            phonenum=request.GET.get('phonenum') #获取用户输入的手机号
            print(phonenum)
            print(code)
            send_sms(str(phonenum),code) #给用户发送验证码
            info='验证码发送成功'
            return HttpResponse(info,content_type='text/text')
        else:
            info = '验证码发送失败'
            return HttpResponse(info, content_type='text/text')

def log_in(request):  #注意函数名不要和包重名
    if request.method=='POST':
        obj=registry.objects.filter(name=request.POST['name'],password=request.POST['password1'])#在数据库中验证用户名和密码是否匹配
        if obj.count()==0:
            form = captcha_form(request.POST)
            context = {'obj': request.POST['name'], 'form': form,'error':'用户名或密码错误(也可能未注册)!'}
            return render(request, "login/login.html",context)
        else:
            print(request.session.get('code'))
            if not request.session.get('code'):
                context={'obj':request.POST['name'],'error':"请先点击发送验证码"}
                print(context)
            elif time.time()>request.session['overtime']:
                context = {'obj': request.POST['name'], 'error': "验证码超时"}
                print(context)
            elif request.POST['code']!=str(request.session['code']):
                context = {'obj': request.POST['name'], 'error': "验证码输入错误"}
                print(context)
                return render(request, "login/login.html", context)  # 返回一个渲染网页给用户
            else:
                context = {'obj': request.POST['name'],'tip':'恭喜你登陆成功'}
                return render(request,"login/homepage.html",context) #点击提交时回到首页并且把用户名传给首页
    else:
        return render(request, "login/login.html")  #返回一个渲染网页给用户

def log_out(request):  #注意函数名不要和包重名

    return redirect("login:首页")

def register(request):  #注意函数名不要和包重名
    if request.method == 'POST':
        name=request.POST['name'] #不允许名字重复
        test =registry.objects.filter(name=name)

        if test.count()!=0:  #证明此时重名
            return render(request, "login/register.html",{'error':'该用户名已经存在!'})

        password1=request.POST['password1']
        password2 = request.POST['password2']

        if password2!=password1:
            return render(request, "login/register.html", {'error': '请输入两次相同的密码!'})

        email=request.POST['email']
        registry.objects.create(name=name,password=password1,email=email)
        obj =name
        context={'obj':obj}
        return render(request,'login/homepage.html',context)#传参过去注册之后自动登录进入主页
    return render(request,"login/register.html")


def user_center(request):#进入个人中心
    if request.GET.get('obj') is None:  # 证明此时用户还没有登陆
        context = {'error': '监测到您还未登录，请先登录。'}
        return render(request, 'login/user_center.html', context)
    obj=request.GET.get('obj')
    print(obj)
    #从数据库获取该用户的全部信息并且显示出来
    detail=registry.objects.filter(name=obj)
    context={'obj':obj,'detail':detail}
    print(detail)
    return render(request,'login/user_center.html',context)

def base(request):#进入首页
    return render(request,'login/base.html')


def edit_profile(request):#编辑个人信息
    if request.GET.get('obj') is None:  # 证明此时用户还没有登陆
        context = {'error': '监测到您还未登录，请先登录。'}
        return render(request, 'login/user_center.html', context)

    obj = request.GET.get('obj')
    print(obj)
    detail = registry.objects.filter(name=obj)  #filter可以用for遍历,get不行
    print(detail)
    if request.method=='GET':
        context = {'obj': obj , 'detail':detail}
        return render(request,'login/edit_profile.html',context)

    if request.method == 'POST':
        email=request.POST['email']
        password1=request.POST['password1']
        password2= request.POST['password2']
        if password1!=password2:
            context={'detail':detail,'obj':obj,'error':'请输入两次相同的密码。'}
            return render(request, 'login/edit_profile.html', context)
        else:
            oupdate=registry.objects.get(name=obj)
            oupdate.email=email
            oupdate.password1=password1
            oupdate.password2 = password2
            oupdate.save()
            context = {'detail': detail, 'obj': obj, 'tip': '恭喜你修改信息成功。'}
        return render(request, 'login/edit_profile.html',context )
    else:
        context = {'detail': detail, 'obj': obj}
    return render(request,'login/edit_profile.html',context)

@login_required(login_url='login:登录')
def change_password(request):#修改个人密码
    if request.method == 'POST':
        form=PasswordChangeForm(data=request.POST,user=request.user)
        if form.is_valid():
            form.save()
            return redirect("login:登录") #改完密码一般要求重新登录
    else:
        form=PasswordChangeForm(user=request.user)
    context={'form': form,'user':request.user}
    return render(request,'login/change_password.html',context)

def ticket_information(request):
    if request.GET.get('obj') is None:  # 证明此时用户还没有登陆
        context = {'tip': '监测到您还未登录，请先登录。'}
        return render(request, 'login/ticket.html', context)
    obj = request.GET.get('obj')
    if request.method=='GET':
        obj=request.GET.get('obj')
        print(obj)
        #获取数据库ticket中的全部数据并显示出来
        detail=ticket.objects.all()
        context = {'obj': obj,'detail':detail}  # 获取用户名
        return render(request,'login/ticket.html',context)
    if request.method=='POST':
        src=request.POST['src']
        det=request.POST['det']
        date=request.POST['date']
        print(src)
        print(det)
        print(date)
        detail=ticket.objects.filter(src=src,det=det,date=date)
        if detail.count()==0:  #证明没有这条信息
            context = {'obj': obj, 'tip': '抱歉，当前没有查到该票信息'}  # 获取用户名
            return render(request, 'login/ticket.html', context)
        else:
            context = {'obj': obj,'detail':detail}  # 获取用户名
            return render(request,'login/ticket.html',context)

def buy_information(request):#进行详细的购买操作,进行车票表的改操作，在购买表增加一条新纪录
    if request.GET.get('obj') is None: #证明此时用户还没有登陆
        context={'tip':'监测到您还未登录，请先登录。'}
        return render(request,'login/ticket.html',context)

    print(request.GET.get('obj'))#用户名
    print(request.GET.get('tid'))#车票编号

    tid=request.GET.get('tid') #车号
    name = request.GET.get('obj')  # 用户名

    detail=ticket.objects.filter(id=tid)

    context = {'obj': name, 'tid':tid,'detail':detail}  # 获取用户名
    if request.method=='GET':
        return render(request, 'login/buy_information.html',context)

    if request.method=='POST':
        type=request.POST['kind']  #购买的票类型
        num=int(request.POST['num'])  #数量
        realname = request.POST['realname']#真实姓名
        idnum=request.POST['idnum']#身份证号
        tupdate=ticket.objects.get(id=tid)#获取ticket的信息
        print(tupdate.soft)
        #根据不同的类型修改票的数量
        if type=='软卧':
            tupdate.soft = int(tupdate.soft) - int(num)
            result=tupdate.soft
        elif type=='硬卧':
            tupdate.hard = int(tupdate.hard) - int(num)
            result = tupdate.soft
        else :
            tupdate.hardseat = int(tupdate.hardseat) - int(num)
            result = tupdate.soft

        if result >= 0:#证明购买成功
            tupdate.save()
            # 存入新表
            bought_ticket.objects.create(tid=tid, tname=tupdate.name, tsrc=tupdate.src, tdet=tupdate.det,
                                         tdate=tupdate.date, type=type, num=num, name=name, realname=realname,
                                         idnum=idnum,buytime=datetime.now())
            context = {'obj': name, 'tid':tid,'tip':"恭喜你买票成功"}  # 获取用户名
            return render(request, 'login/homepage.html', context)
        else:
            detail=ticket.objects.all()
            context = {'obj': name, 'tid': tid, 'tip': "该票已经卖完，请重新选择！",'detail':detail}  # 获取用户名
            return render(request, 'login/ticket.html', context) #重新返回车票信息网页





def bought_information(request):#查看到已经卖到的车票并能在这个页面进行退票
    obj=request.GET.get('obj')
    if request.GET.get('id') is None: #证明这个时候还没有点击退票操作
        print(request.GET.get('obj'))#用户名
         #获取数据库ticket中的全部数据并显示出来，在前端渲染然后进行退票操作
        detail=bought_ticket.objects.filter(name=obj)
        context = {'obj': obj, 'detail': detail}  # 获取用户名
        if detail.count()==0:
            tip='您还没有购买任何车票。'
            context = {'obj': obj,'detail':detail,'error':tip}  # 获取用户名
        return render(request,'login/bought.html',context)

    if request.GET.get('id') is not None:#此时已经点击了退票操作，进行退票
        #获取post请求中的id 加上之前获取到的obj，进行数据库的删除操作
        print("正在退票")
        id=request.GET.get('id')
        bought_ticket.objects.filter(name=obj,id=id).delete()
        detail = bought_ticket.objects.filter(name=obj) #重新获取数据库数据
        tip='恭喜您，您已成功退票。'
        context = {'obj': obj, 'detail': detail, 'tip': tip}  # 获取用户名
        return render(request, 'login/bought.html', context)

mysite_env/mysite/login/templates/login/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/背景.css" />
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
    <script type="text/javascript"src="{% static 'jquery.min.js' %}"></script>
    <script type="text/javascript"src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>

</head>
<body class="class1">
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">车站售票系统</a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav navbar-right">

            <li><a href="{% url 'login:主页' %}?obj={{ obj }}">主页</a>
            <li><a href="{% url 'login:登录' %}">登录</a></li>
            <li><a href="{% url 'login:注册' %}">注册</a></li>
            <li><a href="{% url 'login:退出' %}">退出</a></li></li>

          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

<div class="container-fluid">
    ::before
      <div class="row">
          ::before
        <div class="col-sm-3 col-md-2 sidebar">

          <ul class="nav nav-sidebar">
              ::before

            <li style="margin-top:20px" class="active"><a href="{% url 'login:车票信息' %}?obj={{ obj }}">车票查询</a></li>
            <li><a href="{% url 'login:个人中心' %}?obj={{ obj }}">个人中心</a></li>
            <li><a href="{% url 'login:编辑个人信息' %}?obj={{ obj }}">修改资料</a></li>
            <li><a href="{% url 'login:已购车票' %}?obj={{ obj }}">已购车票</a></li>
            <li><a href="{% url 'login:票务修改' %}?obj={{ obj }}">票务修改</a></li>
            <li><a href="{% url 'login:记录查询' %}?obj={{ obj }}">记录查询</a></li>
          </ul>

        </div>

       {% block content %}{% endblock %}

      </div>

    </div>

</body>


</html>

mysite_env/mysite/login/templates/login/bought.html
{% extends 'login/base.html'%}

{% block title %}
   已购车票
{% endblock %}

{% block content %}
<div class="col-sm-10">
    <h2>欢迎{{ obj }}来到车站售票系统</h2>

    {% if tip is not None %}{% comment %}证明此时要显示的是成功提示{% endcomment %}
        <div class="alert alert-success" role="alert">
            <strong>成功!</strong>{{ tip }}
        </div>
    {% elif error is not None %}
        <div class="alert alert-warning" role="alert">
        <strong>注意!</strong> {{ error }}
      </div>

    {% endif %}

    <button  class="btn btn-sm btn-default"><a href="{% url 'login:个人中心' %}?obj={{ obj }}">回到个人中心</a></button>
    <br><br>

    <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">购买到的车票</h3>
            </div>
            <div class="panel-body">
              <div class="col-md-16">
                <table class="table table-striped">
                    <tr>
                        <td>车型</td>
                        <td>始发站</td>
                        <td>目的站</td>
                        <td>发车日期</td>
                        <td>类型</td>
                        <td>数量</td>
                        <td>用户名</td>
                        <td>姓名</td>
                        <td>身份证号</td>
                        <td>购买时间</td>
                        <td>相关操作</td>
                    </tr>
                    {% for item in detail %}
                        <tr>
                        <td>{{ item.tname }}</td>
                        <td>{{ item.tsrc }}</td>
                        <td>{{ item.tdet }}</td>
                        <td>{{ item.tdate }}</td>
                        <td>{{ item.type }}</td>
                        <td>{{ item.num }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.realname }}</td>
                        <td>{{ item.idnum }}</td>
                        <td>{{ item.buytime }}</td>
                        <td>
                        <button  class="btn btn-default"><a  href="{% url 'login:已购车票' %}?obj={{ obj }}&tid={{ item.tid }}&id={{ item.id }}">退票</a></button>
                        </td>
                        </tr>
                    {% endfor %}
                </table>
              </div>
            </div>
          </div>
</div>
{% endblock %}

mysite_env/mysite/login/templates/login/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body>
<h1>修改密码</h1>
        <a href="{% url 'login:主页' %}">回到主页</a>
        <a href="{% url 'login:个人中心' %}">个人中心</a>
        <a href="{% url 'login:修改密码' %}">修改密码</a>
        <a href="{% url 'login:编辑个人信息' %}">编辑个人信息</a>
        <a href="{% url 'login:退出' %}">退出</a>

<form action="" method="POST">
    {% csrf_token %}
    <p>
        <label for="id_old_password">旧密码:</label>
        <input type="password" name="old_password" autofocus="" required="" id="id_old_password">
    </p>
    <p>
        <label for="id_new_password1">新密码:</label>
        <input type="password" name="new_password1" required="" id="id_new_password1">
        <span class="helptext">
            <ul>
                <li>你的密码不能与你的其他个人信息太相似。</li>
                <li>你的密码必须包含至少 8 个字符。</li>
             <li>你的密码不能是大家都爱用的常见密码。</li>
             <li>你的密码不能全部为数字。</li>
            </ul>
        </span>
        {{ form.errors }}
    </p>

    <p>
        <label for="id_new_password2">新密码确认:</label>
        <input type="password" name="new_password2" required="" id="id_new_password2">
    </p>
    <button type="submit">提交</button>
</form>
</body>
</html>

mysite_env/mysite/login/templates/login/homepage.html
{% extends 'login/base.html'%}

{% block title %}
   首页
{% endblock %}

{% block content %}
{% load static %}
{% load staticfiles %}

<body >
<div class="col-sm-10">

         <h1>欢迎{{ obj }}来到车站售票系统</h1>
                {% if tip is not None %}
                         <div class="alert alert-success" role="alert">
                            <strong>成功!</strong> {{ tip }}
                            </div>
                    {% endif %}
               {% if error is not None %}
                         <div class="alert alert-warning" role="alert">
                            <strong>注意!</strong> {{ error }}
                            </div>
               {% endif %}

        <button type="button" class="btn btn-lg btn-default"><a  href="{% url 'login:车票信息' %}?obj={{ obj }}">点我购买车票</a></button>
        <button type="button" class="btn btn-lg btn-default"><a  href="{% url 'login:个人中心' %}?obj={{ obj }}">进入个人中心</a></button>

</div>
</body>

{% endblock %}

mysite_env/mysite/login/templates/login/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>

</body>
</html>

mysite_env/mysite/login/templates/login/ticket_change.html
{% extends 'login/base.html'%}

{% block title %}
   车票信息修改
{% endblock %}

{% block content %}


<div class="col-sm-10">
    {% if obj is not None %}
    <h2>欢迎{{ obj }}来到车站售票系统</h2>

    {% else %}
    <h2>欢迎来到车站售票系统</h2>
    {% endif %}

    {% if error is not None %}
    <div class="alert alert-danger" role="alert">
        <strong>注意!</strong>{{ error }}
      </div>
    {% endif %}

{% if tip is not None %}
    <div class="alert alert-success" role="alert">
        <strong>成功!</strong>{{ tip }}
      </div>
    {% endif %}

 <button  class="btn btn-sm btn-default"><a href="{% url 'login:主页' %}?obj={{ obj }}">回到首页</a></button>
    <br><br>

{% if tip is None %} {% comment %}tip用来返回管理员校验成功的信息火车票删除成功信息{% endcomment %}
<div class="col-sm-8">
          <div class="panel panel-warning">
            <div class="panel-heading">
              <h3 class="panel-title">管理员身份验证</h3>
            </div>
            <div class="panel-body">
                <h3><span class="label label-info">请输入管理员校验码：</span></h3>
                <form action="" method="POST">
                     {% csrf_token %}
                    <input type="text" name="code" placeholder="请输入校验码">
                    <button class="btn btn-success"type="submit">提交</button>
                </form>
            </div>
          </div>
            </div>



{% else %}

    <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">车票信息 <button style="margin-left: 875px" class="btn btn-sm btn-default"><a href="{% url 'login:新增车票' %}?obj={{ obj }}">新增车票</a></button></h3>

            </div>


            <div class="panel-body">
                <div  class="col-md-20">
                    <table  class="table table-striped">
                     <tr>
                        <td>序号</td>
                        <td>车型</td>
                        <td>始发站</td>
                        <td>目的站</td>
                        <td>发车日期</td>
                        <td>软卧余票</td>
                        <td>软卧价格</td>
                        <td>硬卧余票</td>
                        <td>硬卧价格</td>
                        <td>硬座余票</td>
                        <td>硬座价格</td>
                        <td>修改操作</td>
                        <td>删除操作</td>
                        </tr>
                    {% for item in detail %}
                     <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.src }}</td>
                        <td>{{ item.det }}</td>
                        <td>{{ item.date }}</td>
                        <td>{{ item.soft }}</td>
                        <td style="color: red">{{ item.softprice }}￥</td>
                        <td>{{ item.hard }}</td>
                        <td style="color: red">{{ item.hardprice }}￥</td>
                        <td>{{ item.hardseat }}</td>
                        <td style="color: red">{{ item.hardseatprice }}￥</td>
                        <td>
                        <button  class="btn btn-sm btn-default"><a href="{% url 'login:车票详细信息修改' %}?obj={{ obj }}&tid={{ item.id }}">车票修改</a></button>
                        </td>
                         <td>
                        <button  class="btn btn-sm btn-default"><a href="{% url 'login:删除车票' %}?obj={{ obj }}&tid={{ item.id }}">删除车票</a></button>
                        </td>
                     </tr>
                 {% endfor %}
                          </table>
                     </div>
            </div>
          </div>

    </div>


{% endif %}

{% endblock %}

mysite_env/mysite/login/templates/login/user_center.html
{% extends 'login/base.html'%}

{% block title %}
   个人中心
{% endblock %}
   {% block content %}
<div class="col-sm-10">
     <h1>欢迎你,{{ obj }}</h1> {% comment %}用户名{% endcomment %}

    {% if error is not None %}
    <div class="alert alert-warning" role="alert">
        <strong>注意!</strong>{{ error }}
      </div>
    {% endif %}

      {% comment %}显示用户详细信息{% endcomment %}
      <div class="col-sm-10">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">详细资料</h4>
            </div>
            <div class="panel-body">
              {% if detail is not None %}
                  {% for item in detail %}
                   <h3><span class="label label-info">用户名</span>
                   {{ item.name }}
                   </h3>

                   <h3><span class="label label-info">密码</span>
                    {{ item.password}}
                   </h3>

                   <h3><span class="label label-info">邮箱</span>
                    {{ item.email }}
                   </h3>

                   {% endfor %}
                {% endif %}
            </div>
          </div>


        <button  class="btn btn-default"><a href="{% url 'login:主页' %}?obj={{ obj }}">回到主页</a></button>
        <button class="btn btn-default"><a href="{% url 'login:已购车票' %}?obj={{ obj }}">已购车票</a></button>
        <button class="btn  btn-default"><a href="{% url 'login:编辑个人信息' %}?obj={{ obj }}">编辑个人信息</a></button>
        <button class="btn btn-default"><a href="{% url 'login:退出' %}">退出</a></button>


</div>
{% endblock %}